services:
  database:
    image: mariadb
    container_name: team2-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_USER: team2_user
      MARIADB_PASSWORD: team2_password
      MARIADB_DATABASE: team2db
    volumes:
      - ./src/main/resources/db_config/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 6033:3306

  app:
    container_name: team2-app
    build: .
    ports:
      - 8888:8972
    restart: always
    depends_on:
      - database
    links:
      - database
    platform: linux/amd64
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/team2db
