server:
  port: 8972

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:6033/team2db
    username: team2_user
    password: team2_password

mybatis:
  mapper-locations: mappers/*.xml