server:
  port: 8972
  
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:6033/team2db
    username: team2_user
    password: team2_password
  application:
    name: socket
mybatis:
  mapper-locations: mappers/*.xml
logging:
  file:
    path: /home/ubuntu/log  # 로그 파일 경로 설정
  level:
    root: INFO  # 로그 레벨 설정