server:
  port: 8972 # 이 설정없으면 8080

spring:
  application:
    name: socket # 애플리케이션 이름 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:6033/encore
    username: todo_user
    password: todo_passwd
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   generate-ddl: false
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       format_sql: true 

mybatis:
  mapper-locations: mappers/*.xml
