server:
  port: 8972

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database:3306/team2db
    username: team2_user
    password: team2_password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true


mybatis:
  mapper-locations: mappers/*.xml