server:
  port: 8972
  
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.17.0.1:6033/team2db
    username: team2_user
    password: team2_password
  application:
    name: socket
mybatis:
  mapper-locations: mappers/*.xml
